import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Italiana, Judson } from "next/font/google";
import "./globals.css";
// Global CSS for AOS animations
import "@reimujs/aos/dist/aos.css";
import Navbar from "../components/Layouts/Navbar";
import Footer from "../components/Layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Belitong Adventure",
  description: "Generated by create next app",
};


const italiana = Italiana({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-italiana",
});

const judson = Judson({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-judson",
});

const inter = Inter({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${italiana.variable} ${judson.variable} ${inter.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
